export { MicroGameEngine } from './MicroGameEngine';
export { TemplateFactory } from './TemplateFactory';
export { TriggerEngine } from './TriggerEngine';
export type { ITriggerResult } from './TriggerEngine';
export { PersonalizationEngine } from './PersonalizationEngine';
export type { IGameRecommendation } from './PersonalizationEngine';
export { LeaderboardEngine, LeaderboardWindow } from './LeaderboardEngine';
export type { ILeaderboardEntry, ILeaderboardConfig, ILeaderboardQuery } from './LeaderboardEngine';
export { AchievementEngine, AchievementCategory, AchievementRarity } from './AchievementEngine';
export type { IAchievement, IAchievementReward, IAchievementProgress, IUnlockedAchievement, IDailyChallenge } from './AchievementEngine';
export { SocialEngine, FriendStatus, ChallengeStatus } from './SocialEngine';
export type { IFriendship, IGameChallenge, IShareRecord, ISocialFeedItem, ISocialNotification } from './SocialEngine';
export { AnalyticsEngine, AnalyticsEventType } from './AnalyticsEngine';
export type { IAnalyticsEvent, IFunnelStep, IFunnelAnalysis, IRetentionCohort, IUserAnalytics, IDashboardMetrics } from './AnalyticsEngine';
export { MonetizationEngine, CurrencyType, PremiumTier, AdType } from './MonetizationEngine';
export type { IShopItem, ITransaction, IUserWallet, IAdPlacement, IRevenueSummary } from './MonetizationEngine';
export { ExperimentEngine, ExperimentStatus, MetricType } from './ExperimentEngine';
export type { IExperimentVariant, IMetricDefinition, IExperiment, IMetricPoint, ITargetingRule, IExperimentResult, IExperimentResultVariant, IExperimentMetricResult } from './ExperimentEngine';
export { EmotionEngine, EmotionSource } from './EmotionAIEngine';
export type { IEmotionReading, IBehaviorSnapshot, INarrativeNode, IEmotionHistoryEntry, IEmotionProfile } from './EmotionAIEngine';
export { CloudSyncEngine, SyncStatus, ConflictStrategy } from './CloudSyncEngine';
export type { ISyncData, ISyncPacket, ISyncResult, ISyncConflict, IDeviceRegistration } from './CloudSyncEngine';
export { I18nEngine, Language, TextDirection } from './I18nEngine';
export type { ILocalizedString, ILocaleConfig, ICulturalRule } from './I18nEngine';
