export { MicroGameEngine } from './MicroGameEngine';
export { TemplateFactory } from './TemplateFactory';
export { TriggerEngine } from './TriggerEngine';
export type { ITriggerResult } from './TriggerEngine';
export { PersonalizationEngine } from './PersonalizationEngine';
export type { IGameRecommendation } from './PersonalizationEngine';
export { LeaderboardEngine, LeaderboardWindow } from './LeaderboardEngine';
export type { ILeaderboardEntry, ILeaderboardConfig, ILeaderboardQuery } from './LeaderboardEngine';
export { AchievementEngine, AchievementCategory, AchievementRarity } from './AchievementEngine';
export type { IAchievement, IAchievementReward, IAchievementProgress, IUnlockedAchievement, IDailyChallenge } from './AchievementEngine';
export { SocialEngine, FriendStatus, ChallengeStatus } from './SocialEngine';
export type { IFriendship, IGameChallenge, IShareRecord, ISocialFeedItem, ISocialNotification } from './SocialEngine';
export { AnalyticsEngine, AnalyticsEventType } from './AnalyticsEngine';
export type { IAnalyticsEvent, IFunnelStep, IFunnelAnalysis, IRetentionCohort, IUserAnalytics, IDashboardMetrics } from './AnalyticsEngine';
